#!/bin/bash

set -o pipefail

function usage() {
  cat << EOF
usage: treesum <directory>

Calculate a directory tree's checksum 

Looks at files, directories, and symlinks.
EOF
}

XARGS_WORKERS=${TREESUM_WORKERS:-10}

XARGS_PER_WORKER=${TREESUM_PER_WORKER:-3}

XARGS="xargs -0 -P $XARGS_WORKERS -n $XARGS_PER_WORKER -r -x"

function calculate_file_checksum() {
  find -type f -print0 |\
      $XARGS -I {} sha1sum {} |\
      sort | sha1sum | awk '{print $1}'
}

function calculate_link_checksum() {
  # What constitutes a symlink's checksum is somewhat open to interpretation.
  # Here, we look at the mode, group name, user name, file name, SELinux context,
  # and target filename of the symlink.
  find -type l -print0 |\
      $XARGS stat --printf "%a\0%g\0%n\0%u\0%C\0%N\n" |\
      sort | sha1sum | awk '{print $1}' 
}

function calculate_dir_checksum() {
  # What constitutes a directory's checksum is somewhat open to interpretation
  # Here, we look at the mode, group name, user name, file name, and SELinux context
  # of all files and subdirectories
  find -type d -o -type f -print0 |\
      $XARGS stat --printf "%a\0%g\0%n\0%u\0%C\n" |\
      sort | sha1sum | awk '{print $1}'
}

function run_checksum() {
  filesum=$(calculate_file_checksum)
  linksum=$(calculate_link_checksum)
  dirsum=$(calculate_dir_checksum)
  echo $filesum $dirsum $linksum | sha1sum | awk '{print $1}'
}

function main() {
  DIRECTORY=$1
  
  [ -z $DIRECTORY ] && usage && exit 1

  [ ! -d $DIRECTORY ] && echo "treesum: $DIRECTORY: No such directory" && exit 2

  # normalize directory path
  DIRECTORY=$(readlink -f $DIRECTORY)

  cd $DIRECTORY

  echo $(run_checksum)

}

main $1
